services:
  mongo-db:
    image: mongo:latest
    container_name: my-db
    volumes: 
      - /var/lib/mongo:/data/db
    networks:
      - switch
    env_file:
      - containers.env

  node-app:
    build: .
    container_name: my-node
    depends_on: 
      - mongo-db
    ports:
      - "3000:3000"
    networks:
      - switch
    env_file:
      - containers.env
networks:
  switch:
    driver: bridge

