services:
  mongo-db:
    image: mongodb:latest
    container_name: my-db
    volumes: 
      - /var/lib/mongo:/data/db
    networks:
      - switch

  node-app:
    build: .
    container_name: my-node
    depends_on: 
      - mongo-db
    ports:
      - "3000:3000"
    networks:
      - switch

networks:
  switch:
    driver: bridge

