pipeline{

    agent{label "Hat"}

    stages{
        stage('POLL SCM'){
            steps{
                echo "Pulling source code from git after poll-scm"
                checkout scm
             }
         }
         
         stage('Target Docker'){
             steps{
                 echo "Deploying Multiple container with Docker Compose"
                 sshagent(["cent-key"]) {
                 sh """
                 #copying pulled source code to target server via scp
                 scp -o StrictHostKeyChecking  "./* root@cent:/root/mongodb/"
                 ssh -o StrictHostKeyChecking=no root@cent "
                 cd /mongodb/ && docker build -t my-node .
                 docker compose up -d
                 "
                 """
                 }
              }
            }
     }
 
   post{
        
          success {
                   echo "The Multicontainer Deployment has been successfully finished"
                  }
          cleanup {
                echo "Successfully deployed; Cleaning workspace caches"
                cleanWs
                }
         }                
}

